version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02
     
    steps:
      - checkout
      - run: |
             cd ..
             cd ..
             cd ubuntu
             ls -la
      - run: |
             sudo apt-get update 
             sudo apt-get install cppcheck 
            
      - run: |
             sudo apt-get update 
             sudo apt-get install clang-format 
             
      - run: |
             sudo apt-get update
             sudo apt-get install valgrind
             
      - run: |
             sudo apt-get update
             sudo apt-get install build-essential
             
      - run: |
             sudo apt-get update
             sudo apt-get install g++
             
      - run: |
             sudo apt-get update
             sudo apt-get install cmake
          
      - run: |
             sudo apt-get install libgtest-dev
             cd /usr/src/gtest
             sudo cmake .
             sudo make
             sudo cp -R /usr/src/gtest/*.a /usr/lib/x86_64-linux-gnu
             
      - run: |
             sudo apt-get update
             sudo apt-get install gcovr
             
      - run: |
             mkdir project/cmake-build-debug
             cd project/cmake-build-debug
             cmake ..
             make
             ./project
             ./gtest
             mkdir coverage
             gcovr -r ../ --html -o coverage/coverage.html --html-details
             
             
      - store_artifacts:
             path: project/cmake-build-debug/coverage
             
      - run: |
            cd project/src
            cppcheck --inconclusive --enable=all --language=c --check-config --suppress=missingIncludeSystem --error-exitcode=1 main.c
            cppcheck --inconclusive --enable=all --language=c --check-config --suppress=missingIncludeSystem --error-exitcode=1 stopwatch.c
            cd ..
            cd src_consistent
            cppcheck --inconclusive --enable=all --language=c --check-config --suppress=missingIncludeSystem --error-exitcode=1 consistent.c
            cd ..
            cd src_parallel
            cppcheck --inconclusive --enable=all --language=c --check-config --suppress=missingIncludeSystem --error-exitcode=1 parallel.c
            
      - run: |
            cd project/src
            clang-format -i -style=WebKit main.c
            clang-format -i -style=WebKit stopwatch.c
            cd ..
            cd src_consistent
            clang-format -i -style=WebKit consistent.c
            cd ..
            cd src_parallel
            clang-format -i -style=WebKit parallel.c
             
      - run: |
             cd project/cmake-build-debug
             valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=1 ./project
