version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
     
    steps:
      - checkout
      - run: |
             sudo apt-get update 
             sudo apt-get install cppcheck 
      
      - run: 
            cppcheck main.c
             

   
