version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:202104-01
     
    steps:
      - checkout
      - run: |
             sudo apt-get update 
             sudo apt-get install cppcheck 
      
      - run: |
            cd project/src
            cppcheck main.c
            cppcheck parser_url.c
            cppcheck print.c
            cppcheck gtest.cpp
            
      - run: |
             sudo apt-get update 
             sudo apt-get install clang-format 
            
      - run: |
             cd project/src
             clang-format -i -style=WebKit main.c
             clang-format -i -style=WebKit parser_url.c
             clang-format -i -style=WebKit print.c
             clang-format -i -style=WebKit gtest.cpp
             
      - run: |
             sudo apt-get update
             sudo apt-get install valgrind
             
      - run: |
             sudo apt-get update
             sudo apt-get install build-essential
             
      - run: |
             sudo apt-get update
             sudo apt-get install cmake
             
      - run: |
             sudo apt install checkinstall build-essential autoconf automake
             
      - run: |
             sudo apt-get update
             sudo apt-get install wget
             
      - run: |
             wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
             tar xf release-1.8.0.tar.gz
             cd googletest-release-1.8.0
             cmake -DBUILD_SHARED_LIBS=ON .
             make
             sudo cp -a googletest/include/gtest /usr/include/
             sudo cp -a googletest /usr/src
             sudo cp -a googlemock/gtest/libgtest_main.so googlemock/gtest/libgtest.so /usr/lib/
             
      - run: |
             cd ..
             cd ..
             cd ..
             cd usr/
             cd src
             pwd
             ls -la
             cd googletest
             ls -la
             cd include
             cd gtest
             pwd
             ls -la
          
      #- run: |
       #      sudo apt-get install libgtest-dev
        #     cd /usr/src/gtest
         #    sudo cmake .
          #   sudo make
           #  ls -la
            # cd src
             #ls -la
         
      - run: |
             mkdir project/cmake-built
             cd project/cmake-built
             cmake ..
             make
             
      - run: |
             cd project/cmake-built
             ./gtest
       
      - run: |
             cd project/cmake-build
             valgrind --tool=memcheck --leak-check=yes ./project
             

   
