version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
     
    steps:
      - checkout
      - run: |
             sudo apt-get update 
             sudo apt-get install cppcheck 
      
      - run: |
            cd project/src
            cppcheck main.c
            cppcheck parser_url.c
            cppcheck print.c
            cppcheck gtest.cpp
            
      - run: |
             sudo apt-get update 
             sudo apt-get install clang-format 
            
      - run: |
             cd project/src
             clang-format -i -style=WebKit main.c
             clang-format -i -style=WebKit parser_url.c
             clang-format -i -style=WebKit print.c
             clang-format -i -style=WebKit gtest.cpp
             
      - run: |
             sudo apt-get update
             sudo apt-get install valgrind
             
      - run: |
             sudo apt-get update
             sudo apt-get install build-essential
             
      - run: |
             sudo apt-get update
             sudo apt-get install cmake
          
      - run: |
             sudo apt-get update
             sudo apt-get install libgtest-dev
             cd /usr/src/gtest
             sudo mkdir build
             cd build
             sudo cmake ..
             sudo make
             sudo cp libgtest* /usr/lib/
             cd ..
             sudo rm -rf build
             sudo mkdir /usr/local/lib/gtest
             
      - run: |
             mkdir project/cmake-built
             cd project/cmake-built
             cmake ../
             make
       
      - run: |
             cd project/cmake-build-debug
             valgrind --tool=memcheck --leak-check=yes ./project
             valgrind --tool=memcheck --leak-check=yes ./gtest
             

   
