version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
     
    steps:
      - checkout
      - run: |
             sudo apt-get update 
             sudo apt-get install cppcheck 
      
      - run: |
            cd project/src
            cppcheck main.c
            cppcheck parser_url.c
            cppcheck print.c
            cppcheck gtest.cpp
            
      - run: |
             sudo apt-get update 
             sudo apt-get install clang-format 
            
      - run: |
             cd project/src
             clang-format -i -style=WebKit main.c
             clang-format -i -style=WebKit parser_url.c
             clang-format -i -style=WebKit print.c
             clang-format -i -style=WebKit gtest.cpp
             
      - run: |
             sudo apt-get update
             sudo apt-get install valgrind
       
      - run: |
             cd project/src
             valgrind --tool=memcheck --leak-check=yes main.c
             valgrind --tool=memcheck --leak-check=yes parser_url.c
             valgrind --tool=memcheck --leak-check=yes print.c
             valgrind --tool=memcheck --leak-check=yes gtest.cpp
             

   
